version: '3.6'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx-balancer
    restart: always
    ports:
      - "80:80"
    depends_on:
      - uk-server
      - us-server-1
      - us-server-2
      - common-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  uk-server:
    container_name: uk-server
    build:
      context: ./uk-app-server
      dockerfile: Dockerfile
    image: uk-server:latest
    ports:
      - '8081:8081'

  us-server-1:
    container_name: us-server-1
    build:
      context: ./us-server-1
      dockerfile: Dockerfile
    image: us-server-1:latest
    ports:
      - '8082:8082'

  us-server-2:
    container_name: us-server-2
    build:
      context: ./us-server-2
      dockerfile: Dockerfile
    image: us-server-2:latest
    ports:
      - '8083:8083'

  common-server:
    container_name: common-server
    build:
      context: ./common-server
      dockerfile: Dockerfile
    image: common-server:latest
    ports:
      - '8084:8084'



